# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pr:
  branches:
      include:
      - "*"

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build AccuTreat-API
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/accutreat-api/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build AccuTreat-APP
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/accutreat-app/Dockerfile'
        tags: |
          $(tag)