version: '3.4'

services:
  api:
    image: accutreat-api
    build: './accutreat-api'
    ports:
      - "${API_PORT}:${API_PORT}"
    environment: 
      - ASPNETCORE_URLS=http://+:${API_PORT}
  app:
    image: accutreat-app
    build: './accutreat-app'
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment: 
      - PORT=${APP_PORT}
    stdin_open: true